# Generated by Django 4.1.5 on 2023-05-03 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_viewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
