# Generated by Django 4.1.5 on 2023-05-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0014_remove_item_last_viewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_viewed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
